# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build/publish Docker image & update image version in config

on:
  # TODO: Fix this
  # push:
  #   branches: [ main ]
  #   paths-ignore:
  #     - 'src/test/**'
  #     - 'docker/**'
  #     - 'docker-compose*.yaml'
  #     - '*.md'
  #     - 'LICENSE'
  pull_request:
    branches: [ main ]

jobs:
  call-workflow-image-build-publish:
    uses: felleslosninger/eid-github-workflows/.github/workflows/spring-boot-build-publish-image.yml@main
    with:
      image-name: selvbetjening-onboarding-maskinporten-api
      java-version: 17
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
      registry-url: ${{ secrets.REGISTRY_URL }}
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}